################## Should work for most Linux distributions ##################
# turns input command echo off
alias no-echo="stty -echo"

# quality of life
alias today="date +%Y-%m-%d"

alias clipboard="xargs echo -n | xclip -sel clip" # needs to have "xclip installed"

alias mkdir="mkdir -pv"

alias ..="cd .."
alias ~="cd ~ && clear"

alias q=exit

type ranger 2>&1 >/dev/null && alias r=ranger
alias clear="clear -x"

alias open="xdg-open"

# listings
alias lt="ls -lt"
alias lss="ls -lSs"
alias l1="ls -1"

alias refresh="clear -x && exec bash"

# needs to have "tmux" installed
if type tmux 2>&1 >/dev/null; then
  alias attachmux="tmux attach-session -t"
  alias lsmux="tmux ls"
fi

# Start vim with a Session file
alias vis="${EDITOR} -S"
alias vi="${EDITOR}"
alias vimdiff="${EDITOR} -d"

# more convenient less
# view raw characters
alias lessr="less -r"
alias lessR="less -R"

alias fucking="sudo"
alias please="sudo"

# vim: ft=sh
