" This file is no longer updated and is only intended to use with Vim instead of
" NeoVim, all settings are minimal
" For up-to-date settings, refer to .config/nvim/init.lua
set nocompatible              " be iMproved, required
set encoding=utf-8

" Replacing `esc` in insert mode
inoremap jj <ESC>
inoremap qq <ESC>:x<CR>

"---------------------------------- NORMAL MODE -------------------------------
nnoremap <CR> o<Esc>
augroup CRFix
   autocmd CmdwinEnter * nnoremap <CR> <CR>
   autocmd BufReadPost quickfix nnoremap <CR> <CR>
augroup END

"-------------------------------- THEMES AND GUI ------------------------------

" Columns limits
" highlights the current line
set cursorline

" themes
" 24-bit colors
if &term =~ '256color'
  " disable Background Color Erase (BCE)
  set t_ut=
endif

set ttymouse=xterm2

if has('termguicolors')
  set termguicolors
endif

syntax on

" Highlight trailing white spaces
augroup ExtraWhiteSpaceHi
  au!
  match DiffDelete /\s\+$/
  autocmd BufWinEnter * match DiffDelete /\s\+$/
  autocmd InsertEnter * match DiffDelete /\s\+\%#\@<!$/
  autocmd InsertLeave * match DiffDelete /\s\+$/
  autocmd BufWinLeave * call clearmatches()
augroup END

set textwidth=80
set colorcolumn=+0
augroup ActiveWin
  au!
  autocmd WinEnter * set colorcolumn=+0
  autocmd WinLeave * set colorcolumn=0
augroup END

set background=dark
colorscheme habamax
