#!/bin/bash
CONNECTED=$(xrandr -q | grep ' connected')
NUM_CONNECTED=$(echo "$CONNECTED" | wc -l)
PRIMARY=$(echo "$CONNECTED" | grep "primary" | cut -f1 -d' ')
SECONDARY=$(echo "$CONNECTED" | grep -v "primary" | cut -f1 -d' ')

if ! pgrep i3lock > /dev/null 2>&1; then
  i3-msg restart
  betterlockscreen -u $HOME/pics/wallpapers/onedark.png
fi
