[i3]
# Folder for cached icons
cache_dir = "$HOME/.cache/ixwindow/polybar-icons"

# Size of the icon
size = 24

# Background color of your polybar
color = "#282C34"

# Absolute coordinates of icon
x = 80
y = 3

# Amound of spaces in the title of the module, before title of the window
# This is to be adjusted together with coordinates of the icon to achieve the
# best result
gap = "  "

# Gap per desk is needed for "shifting" the icon and is approximately equal to
# size of the icon, because new desktop icon occupies around this space
gap_per_desk = 24
