#!/bin/bash
SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
source $SCRIPT_DIR/../utilVars

if (( $NUM_CONNECTED > 1 )); then
  autorandr --load horizontal
  exit 0
fi

i3-msg restart
