#!/bin/bash
SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
source $SCRIPT_DIR/../commonPostSwitch

i3-msg '[workspace="1"]' move workspace to output $SECONDARY
i3-msg '[workspace="2"]' move workspace to output $SECONDARY
i3-msg '[workspace="3"]' move workspace to output $PRIMARY
